let my_date = new Date()
console.log(my_date.toString())
console.log(my_date.toDateString())
console.log(my_date.toTimeString())
console.log(my_date.toLocaleString())
console.log(my_date.getFullYear())
console.log(my_date.getMonth())
console.log(my_date.getDate())
console.log(my_date.getDay())
console.log(my_date.getHours())
console.log(my_date.getMinutes())
console.log(my_date.getSeconds())
console.log(my_date.getTime())